const data = [
  {
    id: 1,
    title: 'Vegobolle',
    path: 'vegobolle',
    noOfPortions: 6,
    source: '',
    ingredients: [
      '1 lök',
      '6 vitlöksklyftor',
      '2 chili (om man vill ha lite stark)',
      '4-5msk tomatpure',
      '1/2 påse Formbar färs (~400g)',
      'mycket olivolja',
      '1 msk soja',
      'parmesan',
      'färsk basilika',
      'pasta',
    ],
    steps: [
      'Stek finhackad lök & vitlök i asmycket olivolja tills den mjuknar. Häll på tomatpuré och stek mer. Addera paprikapulver om man har. Ta bort allt.',
      'Koka pasta.',
      'Brassa formbar färs och stek ensamt. Sen addera geggan. Häll på mer olivolja & soja.',
    ],
  },
  {
    id: 2,
    title: 'Vegetarisk lasagne',
    path: 'vegetarisk-lasagne',
    noOfPortions: 6,
    source: 'https://www.coop.se/recept/vegetarisk-lasagne-med-soltorkade-tomater/',
    ingredients: [
      '16 torkade lasagneplattor',
      '2-3 gul lök, hackad',
      '4 vitlöksklyftor',
      '2 msk olivolja',
      '800 g färsk spenat',
      '1 tsk svartpeppar',
      '2 burkar soltorkade tomater (a 285g)',
      '300 g chèvre eller fetaost',
      '6 dl crème fraiche',
      '4 dl vatten',
      '4 dl riven ost',
      'Till servering:',
      'rucola',
      'körsbärstomater',
      'smulad chèvre/feta',
    ],
    steps: [
      'Hacka lök, skiva vitlök.',
      'Fräs löken mjuk i olja i en stekpanna. Tillsätt skivad vitlök och spenat. Stek under omrörning tills spenaten sjunkit ihop. Salta och peppra.',
      'Häll bort oljan från soltorkade tomaterna och finhacka dem. Riv ner chèvren i en skål och rör ihop med crème fraiche, vatten och soltorkade tomater.',
      'Varva pastaplattorna med spenat och oströra i en passande ugnsform. Strö över riven ost och grädda mitt i ugnen enligt anvisning på lasagneförpackningen ca 35 min.',
      'Servera lasagnen med rucola och tomat, ev toppad med smulad chèvre.',
    ],
  },
];

export default data;